import type {
  NinetyDayPlaybook,
  RiskRegister,
  SuccessProbability,
} from "@/lib/types/intelligence";

export const MOCK_PLAYBOOK: NinetyDayPlaybook = {
  phases: [
    {
      name: "Research & Source",
      dayStart: 1,
      dayEnd: 14,
      tasks: [
        {
          title: "Validate Product Opportunity",
          dayStart: 1,
          dayEnd: 3,
          exactSteps: [
            "Search Amazon for 'garlic press' and record top 20 listings' prices, ratings, review counts",
            "Use Jungle Scout / Helium 10 free tier to verify monthly search volume (target: 4,000+)",
            "Read 50 one-star reviews across top 5 competitors — list top 3 recurring complaints",
            "Confirm no patent conflicts via Google Patents search for 'silicone garlic press rocker'",
          ],
          beginnerTip: "Don't skip the patent search. A $0 search now prevents a $10,000+ legal bill later.",
          cost: 0,
          successMetric: "Documented competitive analysis with verified search volume and patent clearance",
        },
        {
          title: "Contact Suppliers on Alibaba",
          dayStart: 4,
          dayEnd: 7,
          exactSteps: [
            "Search Alibaba for 'silicone garlic press' — filter by Trade Assurance, Gold Supplier, 3+ years",
            "Contact top 8 suppliers with standardized RFQ template (include your specific design requirements)",
            "Request MOQ, unit price at 300/500/1000 quantities, lead time, and sample cost",
            "Ask for existing product catalogs and factory certification (ISO, FDA food-grade silicone cert)",
          ],
          beginnerTip: "Send the same message to all suppliers. This makes comparing responses much easier.",
          cost: 0,
          successMetric: "Responses from 5+ suppliers with pricing and capability details",
        },
        {
          title: "Evaluate & Select Supplier",
          dayStart: 8,
          dayEnd: 11,
          exactSteps: [
            "Compare all supplier responses in a spreadsheet: price, MOQ, lead time, certifications, communication quality",
            "Narrow to top 3 suppliers based on price-quality balance",
            "Request samples from top 3 ($40-$80 each including shipping)",
            "Verify supplier legitimacy: check business license, ask for client references, request video call",
          ],
          beginnerTip: "The cheapest supplier is rarely the best. Weight communication quality heavily — a responsive supplier prevents costly misunderstandings.",
          cost: 180,
          successMetric: "3 samples ordered from vetted, verified suppliers",
        },
        {
          title: "Register Amazon Seller Account",
          dayStart: 8,
          dayEnd: 14,
          exactSteps: [
            "Create Amazon Professional Seller account ($39.99/month)",
            "Complete identity verification (passport/driver's license + bank statement)",
            "Set up payment method and bank account for disbursements",
            "Begin Brand Registry application (requires trademark — can use IP Accelerator for $600)",
          ],
          beginnerTip: "Use your legal name exactly as it appears on your ID. Mismatches are the #1 cause of verification delays.",
          cost: 40,
          successMetric: "Active seller account with identity verified and Brand Registry in progress",
        },
      ],
    },
    {
      name: "Sample & Validate",
      dayStart: 15,
      dayEnd: 35,
      tasks: [
        {
          title: "Evaluate Samples",
          dayStart: 15,
          dayEnd: 22,
          exactSteps: [
            "Test all 3 samples against your quality checklist: material feel, cleaning mechanism, clove capacity",
            "Give samples to 5 people and collect honest feedback (friends, family, coworkers)",
            "Compare side-by-side with top Amazon competitor product (buy one for $15-25)",
            "Document defects, improvements needed, and winner selection",
          ],
          beginnerTip: "Be brutally honest about sample quality. It's cheaper to request modifications now than deal with returns later.",
          cost: 25,
          successMetric: "Winner selected with documented quality evaluation and user feedback",
        },
        {
          title: "Negotiate Final Terms & Place Order",
          dayStart: 23,
          dayEnd: 28,
          exactSteps: [
            "Send modification requests to winning supplier with specific changes",
            "Negotiate final unit price (target: $3.45 or below at 300 units)",
            "Agree on payment terms: 30% deposit, 70% before shipping (standard for new relationships)",
            "Place order for 300 units via Alibaba Trade Assurance for buyer protection",
          ],
          beginnerTip: "ALWAYS use Trade Assurance or PayPal for your first order. Never wire transfer to a supplier you haven't visited in person.",
          cost: 1035,
          successMetric: "PO placed with Trade Assurance protection, confirmed delivery date within 25-30 days",
        },
        {
          title: "Develop Brand Assets",
          dayStart: 23,
          dayEnd: 35,
          exactSteps: [
            "Design logo and brand identity (use 99designs or Fiverr — budget $200-400)",
            "Create packaging design with required elements: UPC barcode, brand name, 'Made in China' origin marking",
            "Design Amazon product insert card (warranty registration, review request — within TOS)",
            "Prepare brand story for A+ Content",
          ],
          beginnerTip: "Keep packaging simple but professional. Matte finish with embossed logo creates premium feel at minimal cost.",
          cost: 600,
          successMetric: "Complete brand kit: logo, packaging design, insert card, and brand story draft",
        },
      ],
    },
    {
      name: "List & Launch",
      dayStart: 36,
      dayEnd: 60,
      tasks: [
        {
          title: "Product Photography",
          dayStart: 36,
          dayEnd: 42,
          exactSteps: [
            "Hire product photographer or DIY with lightbox ($30-50 on Amazon)",
            "Shoot 7 images minimum: main image (white background), lifestyle shots, infographic images, size comparison",
            "Edit images to Amazon requirements (1000x1000px minimum, pure white background for main)",
            "Create 1 product video (30-60 seconds showing cleaning mechanism in action)",
          ],
          beginnerTip: "Your main image is the single biggest factor in click-through rate. Invest the most time here.",
          cost: 800,
          successMetric: "7+ optimized images and 1 video ready for upload",
        },
        {
          title: "Create Optimized Listing",
          dayStart: 43,
          dayEnd: 48,
          exactSteps: [
            "Research keywords: use Helium 10 Cerebro or free Amazon autocomplete method",
            "Write title following Amazon formula: Brand + Key Feature + Product Type + Size/Quantity",
            "Write 5 bullet points: lead with benefit, follow with feature, include keywords naturally",
            "Write A+ Content with comparison chart and brand story module",
          ],
          beginnerTip: "Write for humans first, then sprinkle in keywords. Amazon's algorithm rewards conversions, not keyword density.",
          cost: 0,
          successMetric: "Complete listing with keyword-optimized title, bullets, A+ Content, and all images uploaded",
        },
        {
          title: "Launch PPC Campaigns",
          dayStart: 49,
          dayEnd: 55,
          exactSteps: [
            "Create Auto campaign ($15/day) — let Amazon discover relevant keywords",
            "After 3 days, download search term report and identify converting keywords",
            "Create Manual campaign ($20/day) with top 15 converting keywords",
            "Set up negative keywords to eliminate irrelevant traffic",
          ],
          beginnerTip: "Start with Auto campaigns to discover keywords you didn't think of. Move winners to Manual campaigns for better control.",
          cost: 600,
          successMetric: "Active Auto + Manual PPC campaigns with initial performance data",
        },
        {
          title: "FBA Inventory Shipment",
          dayStart: 50,
          dayEnd: 60,
          exactSteps: [
            "Create FBA shipment plan in Seller Central",
            "Print FNSKU labels (or have supplier apply them — $0.03/unit)",
            "Arrange freight forwarding from supplier to Amazon FC",
            "Track shipment and verify check-in at Amazon warehouse",
          ],
          beginnerTip: "Ship to a single fulfillment center for your first shipment (costs slightly more but much simpler to manage).",
          cost: 150,
          successMetric: "300 units checked in at Amazon FBA warehouse, listing active and buyable",
        },
      ],
    },
    {
      name: "Optimize & Scale",
      dayStart: 61,
      dayEnd: 85,
      tasks: [
        {
          title: "PPC Optimization",
          dayStart: 61,
          dayEnd: 70,
          exactSteps: [
            "Analyze 14-day PPC data: identify top 5 keywords by ACOS and conversion rate",
            "Increase bids on high-converting keywords, pause keywords with ACOS > 60%",
            "Add competitor ASINs as Product Targeting campaigns",
            "Test Sponsored Brand ads if Brand Registry is approved",
          ],
          beginnerTip: "Don't panic if ACOS is 40-60% in the first month. Focus on total advertising cost relative to total sales velocity.",
          cost: 400,
          successMetric: "ACOS trending below 35% with consistent daily sales velocity",
        },
        {
          title: "Review Generation Strategy",
          dayStart: 65,
          dayEnd: 75,
          exactSteps: [
            "Enroll in Amazon Vine program if eligible (free, requires Brand Registry)",
            "Ensure product insert encourages reviews within Amazon TOS (no incentivized reviews)",
            "Follow up on buyer-seller messaging (within Amazon's guidelines)",
            "Monitor and respond to all reviews within 24 hours",
          ],
          beginnerTip: "Never ask for 'positive' reviews — it violates TOS. Simply ask for 'honest feedback'.",
          cost: 0,
          successMetric: "10+ reviews with average rating above 4.0",
        },
        {
          title: "Analyze Performance & Plan Reorder",
          dayStart: 75,
          dayEnd: 85,
          exactSteps: [
            "Calculate actual vs projected unit economics (compare real Amazon fees to estimates)",
            "Assess sell-through rate and project inventory depletion date",
            "If selling 5+ units/day: place reorder for 500 units (negotiate better pricing)",
            "If selling 2-4 units/day: investigate listing optimization opportunities before reorder",
          ],
          beginnerTip: "Your reorder lead time is 25-30 days. Start the process when you have 30-45 days of inventory remaining.",
          cost: 0,
          successMetric: "Clear performance data, reorder decision made based on actual sales velocity",
        },
      ],
    },
  ],
  weeklyMilestones: [
    { week: 1, milestone: "Competitive analysis complete, suppliers contacted", kpi: "5+ supplier responses received" },
    { week: 2, milestone: "Samples ordered, Amazon account created", kpi: "3 samples in transit, seller account verified" },
    { week: 3, milestone: "Samples received and evaluated", kpi: "Winner selected with quality documentation" },
    { week: 4, milestone: "Production order placed", kpi: "PO confirmed with Trade Assurance, delivery date locked" },
    { week: 5, milestone: "Brand assets in development", kpi: "Logo approved, packaging design 80% complete" },
    { week: 6, milestone: "Photography complete", kpi: "7+ images edited and ready for upload" },
    { week: 7, milestone: "Listing created and optimized", kpi: "Listing live with A+ Content and all images" },
    { week: 8, milestone: "Inventory shipped to FBA", kpi: "Shipment in transit to Amazon warehouse" },
    { week: 9, milestone: "Product live and selling", kpi: "First organic + PPC sales recorded" },
    { week: 10, milestone: "PPC campaigns running", kpi: "Auto + Manual campaigns active, daily spend on target" },
    { week: 11, milestone: "Optimization in progress", kpi: "ACOS trending downward, 5+ reviews accumulated" },
    { week: 12, milestone: "Reorder decision made", kpi: "Sell-through rate calculated, reorder placed if warranted" },
  ],
  day1Actions: [
    "Search Amazon for 'garlic press' and screenshot top 20 results with prices",
    "Create Alibaba account and save 10 potential suppliers to favorites",
    "Set up a dedicated email for Amazon business communications",
    "Create a Google Sheet for tracking competitor analysis data",
    "Block 2 hours daily in your calendar for the next 2 weeks",
  ],
  goLiveTargetDay: 55,
};

export const MOCK_RISK_REGISTER: RiskRegister = {
  risks: [
    {
      title: "Account Suspension",
      description: "New Amazon seller accounts face heightened scrutiny. Any TOS violation can result in immediate suspension with lengthy appeal process.",
      likelihood: 2,
      impact: 5,
      beginnerMultiplier: 2.5,
      adjustedSeverity: 25.0,
      earlyWarningSignals: ["Policy warning emails from Amazon", "Sudden listing deactivation", "Request for additional documentation"],
      mitigation: "Read and follow Amazon TOS exactly. Never incentivize reviews. Use only approved communication channels.",
      contingency: "Prepare appeal letter template in advance. Document all business processes for compliance evidence.",
      isBeginnerSpecific: true,
    },
    {
      title: "Supplier Quality Failure",
      description: "Production batch quality differs significantly from approved samples, leading to high return rate or negative reviews.",
      likelihood: 3,
      impact: 4,
      beginnerMultiplier: 1.8,
      adjustedSeverity: 21.6,
      earlyWarningSignals: ["Supplier communication becomes less responsive", "Sample revision quality drops", "Delivery timeline starts slipping"],
      mitigation: "Use Trade Assurance. Order pre-shipment inspection ($200-300). Define quality standards in PO.",
      contingency: "Have backup supplier identified. Keep 30% of capital in reserve for emergency reorder.",
      isBeginnerSpecific: false,
    },
    {
      title: "PPC Cost Overrun",
      description: "Advertising costs exceed budget due to high competition or poor targeting, eroding margins before organic rankings develop.",
      likelihood: 4,
      impact: 3,
      beginnerMultiplier: 2.0,
      adjustedSeverity: 24.0,
      earlyWarningSignals: ["ACOS consistently above 50% after week 2", "CPC climbing week over week", "Low conversion rate (<10%)"],
      mitigation: "Set daily budget caps. Start with Auto campaigns to find converting keywords. Pause non-performers aggressively.",
      contingency: "Reduce PPC spend to $10/day minimum and focus on organic ranking through listing optimization.",
      isBeginnerSpecific: true,
    },
    {
      title: "Inventory Stockout",
      description: "Product sells faster than expected, leading to stockout that kills organic ranking momentum.",
      likelihood: 3,
      impact: 3,
      beginnerMultiplier: 1.5,
      adjustedSeverity: 13.5,
      earlyWarningSignals: ["Selling 8+ units/day consistently", "Inventory dropping below 30-day supply", "Reorder lead time exceeds remaining inventory days"],
      mitigation: "Track daily sales velocity from day 1. Set reorder trigger at 45-day inventory level.",
      contingency: "Air freight emergency restock (2x cost but 7-day delivery vs 30-day sea freight).",
      isBeginnerSpecific: false,
    },
    {
      title: "Copycat Competition",
      description: "Successful product attracts knockoff sellers who undercut on price, compressing margins.",
      likelihood: 3,
      impact: 3,
      beginnerMultiplier: 1.2,
      adjustedSeverity: 10.8,
      earlyWarningSignals: ["New listings with similar images/titles", "Sudden increase in keyword competition", "Buy box rotation begins"],
      mitigation: "File Brand Registry immediately. Design distinctive packaging. Build review moat fast.",
      contingency: "Differentiate with bundling (garlic press + peeler set) or color variants exclusive to your brand.",
      isBeginnerSpecific: false,
    },
    {
      title: "Negative Review Spiral",
      description: "Early negative reviews (even 2-3) on a new listing can tank conversion rate before positive reviews accumulate.",
      likelihood: 3,
      impact: 4,
      beginnerMultiplier: 1.5,
      adjustedSeverity: 18.0,
      earlyWarningSignals: ["First review is 1-2 stars", "Return rate exceeds 5%", "Customer questions reveal product confusion"],
      mitigation: "Ensure product quality matches/exceeds sample. Include clear usage instructions. Respond to negative reviews professionally.",
      contingency: "Enroll in Vine program to accelerate review collection. Improve listing clarity based on complaint patterns.",
      isBeginnerSpecific: true,
    },
    {
      title: "Customs/Import Delay",
      description: "Shipment delayed at customs due to missing documentation or random inspection, pushing launch timeline.",
      likelihood: 2,
      impact: 3,
      beginnerMultiplier: 2.0,
      adjustedSeverity: 12.0,
      earlyWarningSignals: ["Freight forwarder flags documentation gaps", "Customs hold notification", "Port congestion reports in news"],
      mitigation: "Use experienced freight forwarder. Ensure all documentation (commercial invoice, packing list, HS codes) is correct.",
      contingency: "Build 10-day buffer into launch timeline for customs delays.",
      isBeginnerSpecific: true,
    },
    {
      title: "Cash Flow Crunch",
      description: "Amazon's 14-day payment cycle combined with reorder deposits creates cash flow gap for undercapitalized sellers.",
      likelihood: 3,
      impact: 3,
      beginnerMultiplier: 2.0,
      adjustedSeverity: 18.0,
      earlyWarningSignals: ["Bank balance below $500 after all committed expenses", "Reorder needed but funds not yet disbursed", "Unexpected Amazon fees reduce disbursement"],
      mitigation: "Maintain $500+ cash reserve at all times. Track Amazon disbursement schedule. Delay reorder if necessary.",
      contingency: "Apply for Amazon Lending (available after 3 months of sales history) or use 0% intro APR credit card.",
      isBeginnerSpecific: true,
    },
    {
      title: "Listing Suppression",
      description: "Amazon suppresses listing due to keyword violations, restricted terms, or intellectual property complaint.",
      likelihood: 2,
      impact: 4,
      beginnerMultiplier: 1.8,
      adjustedSeverity: 14.4,
      earlyWarningSignals: ["Listing appears in Seller Central but not in search results", "Health notification in Account Health dashboard", "Sudden drop to zero impressions"],
      mitigation: "Avoid restricted terms (FDA-regulated claims, competitor brand names). Run listing through Amazon's style guide checklist.",
      contingency: "Open case immediately with Seller Support. Have backup listing draft ready for quick re-creation if needed.",
      isBeginnerSpecific: false,
    },
    {
      title: "Exchange Rate Fluctuation",
      description: "USD/CNY exchange rate shifts between deposit and final payment, increasing effective unit cost.",
      likelihood: 2,
      impact: 2,
      beginnerMultiplier: 1.0,
      adjustedSeverity: 4.0,
      earlyWarningSignals: ["CNY strengthening trend in financial news", "Supplier requests price adjustment", "Large gap between quote date and payment date"],
      mitigation: "Negotiate fixed USD pricing with supplier. Pay promptly to minimize exposure window.",
      contingency: "Absorb up to 5% cost increase. Beyond 5%, renegotiate or find alternative supplier.",
      isBeginnerSpecific: false,
    },
  ],
  topBeginnerRisk: "Account Suspension — new accounts face heightened scrutiny and beginners are most likely to accidentally violate TOS. This is the single highest-severity risk due to the 2.5x beginner multiplier.",
  unmitigatableRisks: [
    "Amazon algorithm changes that affect organic ranking — no seller can control or predict these",
    "Category-wide price compression driven by large-scale Chinese sellers entering the market",
  ],
};

export const MOCK_SUCCESS_PROBABILITY: SuccessProbability = {
  overallScore: 72,
  confidenceInterval: [58, 82],
  dimensions: [
    {
      name: "marketDemand",
      label: "Market Demand",
      score: 16,
      explanation: "4,200+ monthly searches with clear pain points in existing products. Demand is verified and stable year-round with Q4 uplift.",
    },
    {
      name: "competitivePosition",
      label: "Competitive Position",
      score: 14,
      explanation: "Differentiated design addresses top 3 complaints. However, one competitor has massive review moat (12,000+) creating social proof barrier.",
    },
    {
      name: "executionFeasibility",
      label: "Execution Feasibility",
      score: 15,
      explanation: "Simple product, clear playbook, FBA handles logistics. Main execution risk is first-time seller learning curve on PPC and listing optimization.",
    },
    {
      name: "financialViability",
      label: "Financial Viability",
      score: 14,
      explanation: "53% gross margin is strong. $4,342 launch cost fits budget. Concern: thin cash reserve ($658) leaves little room for unexpected costs.",
    },
    {
      name: "timingAlignment",
      label: "Timing Alignment",
      score: 13,
      explanation: "No seasonal dependency for launch timing. Q4 presents both opportunity (higher volume) and risk (inventory planning complexity).",
    },
  ],
  failureScenarios: [
    {
      scenario: "Account suspension in first 90 days due to accidental TOS violation",
      probability: 8,
      trigger: "Incentivized reviews, restricted keyword usage, or documentation issues during verification",
    },
    {
      scenario: "Product quality issues leading to >10% return rate and negative review spiral",
      probability: 12,
      trigger: "Skipping pre-shipment inspection or accepting supplier's quality assurance without independent verification",
    },
    {
      scenario: "PPC costs consuming all margin with no path to organic rankings",
      probability: 15,
      trigger: "Listing conversion rate below 8% due to poor images or unoptimized copy, making PPC unsustainable",
    },
    {
      scenario: "Cash flow crunch preventing reorder when product gains traction",
      probability: 10,
      trigger: "Unexpected Amazon fees, refund costs, or reorder deposit needed before first Amazon disbursement",
    },
  ],
  honestAssessment: "This product has a genuine shot at generating $3,000-$5,000/month in revenue within 6-8 months if executed well. The 72% success probability reflects solid fundamentals (real demand, good margins, manageable complexity) tempered by the inherent risks of being a first-time seller. The biggest threat isn't the product or market — it's execution errors that beginners typically make: rushing the launch, skimping on product photography, or mismanaging PPC budgets. The difference between the 58% floor and 82% ceiling almost entirely depends on how disciplined you are about following the playbook step-by-step rather than taking shortcuts. This is not a get-rich-quick opportunity — it's a legitimate small business that requires 15-20 hours/week of focused work for the first 3 months.",
};
