import type { ProductGradeResult } from "@/lib/types/urlAnalysis";

export const MOCK_GRADE_RESULT: ProductGradeResult = {
  overallGrade: "B+",
  overallScore: 76,
  dimensions: [
    {
      name: "listingQuality",
      score: 15,
      maxScore: 20,
      grade: "B",
      rationale: "Title is keyword-rich but slightly long at 149 characters. Bullets lead with benefits but the 5th bullet is feature-only without a customer outcome. Description lacks structured HTML formatting and has no brand story section.",
      keyEvidence: "Title contains 12 relevant keywords; bullet 5 is pure spec ('PRE-OILED & READY') without explaining why the buyer cares.",
      topIssue: "Description is a single paragraph — A+ Content or formatted HTML would improve scan-ability and conversion.",
      quickWin: "Rewrite bullet 5 to lead with the benefit: 'SKIP THE PREP — Arrives pre-oiled with food-safe mineral oil so you can start chopping the day it arrives.'",
    },
    {
      name: "reviewSentiment",
      score: 17,
      maxScore: 20,
      grade: "A-",
      rationale: "4.6-star rating with 3,847 reviews is strong social proof. Sentiment is 68% positive with clear praise for the juice groove design. Negative reviews cluster around warping after dishwasher use — a fixable messaging issue, not a product flaw.",
      keyEvidence: "Top praise: 'juice groove is a game changer' (312 mentions). Top complaint: 'warped after dishwasher' (89 mentions, all user error — listing says hand-wash only).",
      topIssue: "The hand-wash-only instruction is buried in the description. Customers miss it and blame the product.",
      quickWin: "Add 'HAND WASH ONLY' prominently to bullet 2 or 3 — most dishwasher complaints would disappear.",
    },
    {
      name: "competitivePosition",
      score: 14,
      maxScore: 20,
      grade: "B-",
      rationale: "BSR #2,341 is solid but not dominant in Kitchen. Price at $34.99 is above category median ($27.99). Review count trails the #1 competitor (8,200 reviews) by more than 50%. The 3-piece set differentiator is strong but 4 of the top 10 competitors now offer sets too.",
      keyEvidence: "Category leader: 'RoyalCraft Premium Bamboo Board' at $29.99 with 8,200 reviews and BSR #412. This product's 3-piece angle is being copied.",
      topIssue: "Price premium of $5–7 over competitors isn't justified by visible differentiation in the listing.",
      quickWin: "Add a comparison infographic image showing the set vs single-board competitors — justify the price visually.",
    },
    {
      name: "profitPotential",
      score: 16,
      maxScore: 20,
      grade: "B+",
      rationale: "Estimated landed cost $8.50/set, Amazon fees ~$9.80, net margin ~$16.69/unit (47.7%). BSR implies ~450 units/month (~$15,750/month revenue). Referral fee is standard 15%. FBA fees are manageable due to lightweight material.",
      keyEvidence: "Bamboo sets source at $2.80–3.50/unit FOB Fujian province. Shipping + duties ~$5.00–5.50/unit landed. Total COGS ~$8.50.",
      topIssue: "PPC costs at $2.50/click in this category eat into margin — need organic rank improvement to reduce ad dependency.",
      quickWin: "Target long-tail keywords ('bamboo cutting board set with juice groove handles') where CPC drops to $0.80–1.20.",
    },
    {
      name: "marketMomentum",
      score: 14,
      maxScore: 20,
      grade: "B-",
      rationale: "BSR has been flat over 90 days (range 2,100–2,600). Review velocity is ~85/month — healthy but not accelerating. Category is mature with slow growth. No seasonal spike expected outside Q4 holiday gifting.",
      keyEvidence: "90-day BSR trend: stable with no breakout signal. Google Trends for 'bamboo cutting board' flat YoY. Category growth ~3% annually.",
      topIssue: "No momentum catalyst — product is in maintenance mode, not growth mode.",
      quickWin: "Launch a Subscribe & Save option for the mineral oil refill (creates recurring touchpoint and boosts BSR).",
    },
  ],
  strengths: [
    "Strong review sentiment (4.6 stars, 3,847 reviews) with clear VOC praise for the juice groove design",
    "Healthy profit margin (~47.7%) with low sourcing cost and manageable Amazon fees",
    "3-piece set format creates natural price anchoring and perceived value vs single-board competitors",
  ],
  criticalWeaknesses: [
    "Hand-wash instruction buried in description — driving preventable 1-star reviews from dishwasher damage",
    "Price premium ($5–7 above competitors) not visually justified in listing images or copy",
    "No market momentum — flat BSR, no review velocity acceleration, mature category with slow growth",
  ],
  gradeSummary: "This is a solid B+ product with strong fundamentals — good margin, genuine customer love for the juice groove, and decent review volume. The gap to A-tier is primarily a listing optimization problem, not a product problem. Fixing the hand-wash messaging, adding competitive comparison imagery, and targeting long-tail PPC keywords could push this from B+ to A- within 60 days. The biggest strategic risk is the flat market momentum — this product needs a differentiation refresh (gift packaging, mineral oil subscription, exclusive colorways) to avoid slow erosion as competitors copy the 3-piece set format.",
  improvementPotential: 89,
  improvedGrade: "A-",
};
